on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          cargo build
          cargo test
          cargo clippy -- -Dwarnings

  validate_schema:
    runs-on: ubuntu-latest
    needs: build_and_test
    # if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Test schema
        run: |
            cp schema/data-model-schema.json schema/data-model-schema.json.orig
            cargo run
            # assert the generated and versioned file equal
            diff -u schema/data-model-schema.json schema/data-model-schema.json.orig
