on: [push]

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: CI
        run: |
          cargo build
          cargo test
          cargo clippy -- -Dwarnings
